(ns motodata-clj.people-map)

(defn remap [f l]
  (or ({["Dave" "Symonds"] ["Dave" "Simmonds"],
    ["Xian" "He"] ["Zi Xian" "He"],
    ["Daniel" "Webb"] ["Danny" "Webb"],
    ["Georg" "Fr[0m~vhlich"] ["Georg" "Froehlich"],
    ["Shouya" "Tomizawa"] ["Shoya" "Tomizawa"],
    ["Jesco" "Raffin"] ["Jesko" "Raffin"],
    ["Simone" "Grotzki giorgi"] ["Simone" "Grotzkyj"],
    ["Antonio" "Elias"] ["Toni" "Elias"],
    ["Steve" "Bonsey"] ["Stevie" "Bonsey"],
    ["Kevin" "Coghlan"] ["Kev" "Coghlan"],
    ["Patrick vd" "Waarsenburg"] ["Patrick" "Vd Waarsenburg"],
    ["Shinichi" "Itoh"] ["Shinichi" "Ito"],
    ["Brett" "Symonds"] ["Brett" "Simmonds"],
    ["Radek" "Rous"] ["Radomil" "Rous"],
    ["Fabrizio" "Perren"] ["Fabricio" "Perren"],
    ["Tobias" "Siet"] ["Tobias" "Siegert"],
    ["Zhao" "Huang shi"] ["Shi zhao" "Huang"],
    ["Niccolo" "Antonell"] ["Niccolò" "Antonelli"],
    ["Thierry vd" "Bosch"] ["Thierry" "Van Den Bosch"],
    ["Suhathai" "Chamsub"] ["Suhathai" "Chaemsap"],
    ["Pol" "Ergaro"] ["Pol" "Espargaro"],
    ["Daniel" "Pedrosa"] ["Dani" "Pedrosa"],
    ["Chin Feng" "Ho"] ["Chi fung" "Ho"],
    ["Yuuichi" "Yanagisa"] ["Yuuichi" "Yanagisawa"],
    ["Decha" "Krisart"] ["Decha" "Kraisart"],
    ["Jarno vd" "Marel"] ["Jarno" "Van Der Marel"],
    ["Yuuchi" "Yanagisa"] ["Yuuichi" "Yanagisawa"],
    ["Michaele" "Pirro"] ["Michele" "Pirro"],
    ["Patrick vd" "Waarse"] ["Patrick" "Vd Waarsenburg"],
    ["Alex" "Ergaro"] ["Alex" "Espargaro"],
    ["Michel" "Alexis"] ["Alexis" "Michel"],
    ["Juan Francisco" "Gu"] ["Juanfran" "Guevara"],
    ["Henk vd" "Lagemaat"] ["Henk" "Vd Lagemaat"],
    ["Jarno" "Vd marel"] ["Jarno" "Van Der Marel"],
    ["Julio" "Simon"] ["Julian" "Simon"],
    ["Sebastien" "Le grelle"] ["Sebastien" "Legrelle"],
    ["Daijiro" "Katoh"] ["Daijiro" "Kato"],
    ["Jurgen vd" "Goorbergh"] ["Jurgen" "Vd Goorbergh"]} [f l]) [f l]))
