(ns motodata-clj.people-map)

(defn remap [f l]
  (or ({["Dave" "Symonds"] ["Dave" "Simmonds"],
    ["Xian" "He"] ["Zi xian" "He"],
    ["Xian" "He zi"] ["Zi xian" "He"],
    ["Daniel" "Webb"] ["Danny" "Webb"],
    ["Tekkyu" "Kayoh"] ["Tekkyu" "Kayo"],
    ["Luca" "Gruenwald"] ["Luca" "Gr\u00DCnwald"],
    ["Luca" "Gr\u00FCnwald"] ["Luca" "Gr\u00DCnwald"],
    ["Alex" "Mari\u00F1elare"] ["Alex" "Mari\u00D1elarena"],
    ["Andreas" "G\u00F6bel"] ["Andreas" "G\u00D6bel"],
    ["Jarno" "M\u00FCller"] ["Jarno" "M\u00DCller"],
    ["Daniel" "Pi\u00F1era"] ["Daniel" "Pi\u00D1era"],
    ["Muhammad" "Zulfa"] ["Zulfahmi" "Khairuddin"],
    ["Jason" "Vincent"] ["Jay" "Vincent"],
    ["Klaus" "N\u00F6hles"] ["Klaus" "N\u00D6hles"]
    ["Jascha" "B\u00FCch"] ["Jascha" "Buech"],
    ["Georg" "Fr\u00F6hlich"] ["Georg" "Froehlich"],
    ["Shouya" "Tomizawa"] ["Shoya" "Tomizawa"],
    ["Jason" "O'hallora"] ["Jason" "Ohalloran"],
    ["Jesco" "Raffin"] ["Jesko" "Raffin"],
    ["Simone" "Grotzki giorgi"] ["Simone" "Grotzkyj"],
    ["Antonio" "Elias"] ["Toni" "Elias"],
    ["Steve" "Bonsey"] ["Stevie" "Bonsey"],
    ["Kevin" "Coghlan"] ["Kev" "Coghlan"],
    ["Patrick vd" "Waarsenburg"] ["Patrick" "Vd waarsenburg"],
    ["Shinichi" "Itoh"] ["Shinichi" "Ito"],
    ["Brett" "Symonds"] ["Brett" "Simmonds"],
    ["Radek" "Rous"] ["Radomil" "Rous"],
    ["Fabrizio" "Perren"] ["Fabricio" "Perren"],
    ["Tobias" "Siet"] ["Tobias" "Siegert"],
    ["Zhao" "Huang shi"] ["Shi zhao" "Huang"],
    ["Niccolo" "Antonell"] ["Niccol\u00F2" "Antonelli"],
    ["Niccolo" "Antonelli"] ["Niccol\u00F2" "Antonelli"],
    ["Thierry vd" "Bosch"] ["Thierry" "Van den bosch"],
    ["Suhathai" "Chamsub"] ["Suhathai" "Chaemsap"],
    ["Pol" "Ergaro"] ["Pol" "Espargaro"],
    ["Daniel" "Pedrosa"] ["Dani" "Pedrosa"],
    ["Chin Feng" "Ho"] ["Chi fung" "Ho"],
    ["Yuuichi" "Yanagisa"] ["Yuuichi" "Yanagisawa"],
    ["Decha" "Krisart"] ["Decha" "Kraisart"],
    ["Jarno vd" "Marel"] ["Jarno" "Van der marel"],
    ["Yuuchi" "Yanagisa"] ["Yuuichi" "Yanagisawa"],
    ["Michaele" "Pirro"] ["Michele" "Pirro"],
    ["Patrick vd" "Waarse"] ["Patrick" "Vd waarsenburg"],
    ["Alex" "Ergaro"] ["Alex" "Espargaro"],
    ["Michel" "Alexis"] ["Alexis" "Michel"],
    ["Juan francisco" "Gu"] ["Juanfran" "Guevara"],
    ["Henk vd" "Lagemaat"] ["Henk" "Vd lagemaat"],
    ["Jarno" "Vd marel"] ["Jarno" "Van der marel"],
    ["Julio" "Simon"] ["Julian" "Simon"],
    ["Sebastien" "Le grelle"] ["Sebastien" "Legrelle"],
    ["Daijiro" "Katoh"] ["Daijiro" "Kato"],
    ["Jurgen vd" "Goorbergh"] ["Jurgen" "Vd goorbergh"],
    ["Esteve" "Rabat"] ["Tito" "Rabat"],
    ["Isaac" "Vi\u00F1ales"] ["Isaac" "Vi\u00D1ales"],
    ["Maverick" "Vi\u00F1ales"] ["Maverick" "Vi\u00D1ales"]} [f l]) [f l]))
